// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmAxAo3_YcofTxEODaN1xg0vBuZeY11s0',
    appId: '1:761185750489:web:2671750d96b35135799dc8',
    messagingSenderId: '761185750489',
    projectId: 'school-erp-e478e',
    authDomain: 'school-erp-e478e.firebaseapp.com',
    storageBucket: 'school-erp-e478e.firebasestorage.app',
    measurementId: 'G-D41EZCJF1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLkhPW4QV2FTrgGMUJEY5Q3L4qv_AhvjM',
    appId: '1:761185750489:android:60f71fe130332ae4799dc8',
    messagingSenderId: '761185750489',
    projectId: 'school-erp-e478e',
    storageBucket: 'school-erp-e478e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_CRk5RqAuYH8xD4auup5g3knRqaBpvuI',
    appId: '1:761185750489:ios:f671ead7074bab48799dc8',
    messagingSenderId: '761185750489',
    projectId: 'school-erp-e478e',
    storageBucket: 'school-erp-e478e.firebasestorage.app',
    iosBundleId: 'com.mushtaq.schoolErp',
  );
}
